jp2/* Update lib jasper to 2.0.33. Code cleanly compilles, but there is still some problem. Will be solved later.

diff --git a/jp2/test/bin/run_test_1 b/jp2/test/bin/run_test_1
--- a/jp2/test/bin/run_test_1
+++ b/jp2/test/bin/run_test_1
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/env bash
 # Copyright (c) 2016 Michael David Adams
 ################################################################################
 
@@ -21,11 +21,52 @@ top_dir="$cmd_dir/../.."
 data_dir="$top_dir/data"
 
 imginfo="$abs_top_builddir/src/appl/imginfo"
+jasper="$abs_top_builddir/src/appl/jasper"
 
 ################################################################################
 
-good_list=($data_dir/test/good/*.*)
-bad_list=($data_dir/test/bad/*.*)
+internal_testing_mode="${JAS_INTERNAL_TESTING_MODE:-0}"
+
+verbose=0
+if [ $# -ge 1 ]; then
+	verbose=1
+fi
+
+################################################################################
+
+# Decoder tests for valid data.
+good_list=()
+for file in "$data_dir"/test/good/*.*; do
+	skip=0
+	if [ "$internal_testing_mode" -eq 0 ]; then
+		case "$file" in
+		*.mif)
+			skip=1;;
+		esac
+	fi
+	if [ "$skip" -eq 0 ]; then
+		good_list+=("$file")
+	fi
+done
+
+# Decoder tests for invalid data.
+bad_list=()
+for file in "$data_dir"/test/bad/*.*; do
+	skip=0
+	if [ "$internal_testing_mode" -eq 0 ]; then
+		case "$file" in
+		*.mif)
+			skip=1;;
+		esac
+	fi
+	if [ "$skip" -eq 0 ]; then
+		bad_list+=("$file")
+	fi
+done
+
+# Encoder tests that should fail.
+enc_list=()
+enc_list+=("$data_dir"/test/good/109-PoC.jp2)
 
 error_count=0
 
@@ -40,7 +81,7 @@ fi
 echo "JPEG Turbo Library version: $jpeg_turbo_lib_version"
 
 echo "############################################################"
-echo "Testing valid data sets"
+echo "PART 1: Decoder tests --- valid data sets"
 echo "############################################################"
 
 for in_file in "${good_list[@]}"; do
@@ -60,7 +101,7 @@ done
 echo "############################################################"
 
 echo "############################################################"
-echo "Testing invalid data sets"
+echo "PART 2: Decoder tests --- invalid data sets"
 echo "############################################################"
 
 for in_file in "${bad_list[@]}"; do
@@ -128,6 +169,34 @@ for in_file in "${bad_list[@]}"; do
 		error_count=$((error_count + 1))
 	fi
 done
+echo "############################################################"
+
+echo "############################################################"
+echo "PART 3: Encoder tests"
+echo "############################################################"
+
+for in_file in "${enc_list[@]}"; do
+	echo "############################################################"
+	echo "Input file: $in_file"
+	special_asan_options=()
+	special_asan_options+=(exitcode=10)
+	special_asan_options+=(allocator_may_return_null=true)
+	special_asan_options+=(detect_leaks=false)
+	expected_status=1
+	if [ "$verbose" -ge 1 ]; then
+		echo "Running ASAN_OPTIONS=${special_asan_options[*]} $jasper -f $in_file -T jp2 -F - > /dev/null"
+	fi
+	ASAN_OPTIONS="${special_asan_options[*]}" \
+	  "$jasper" -f "$in_file" -T jp2 -F - > /dev/null
+	status=$?
+	if [ "$status" -ne "$expected_status" ]; then
+		echo "ERROR: imginfo command had unexpected exit status " \
+		  "(expected $expected_status got $status)"
+		error_count=$((error_count + 1))
+	fi
+done
+echo "############################################################"
+
 echo "############################################################"
 
 echo "error count: $error_count"
